/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.pololer.spjaprak;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 * Class GUI_AnimeFilm merupakan class GUI berbasis Java Swing yang menyediakan
 * antarmuka grafis khusus untuk mengelola data Anime Film (movie) dalam Sistem
 * Penjadwalan Tayang Anime (SPJA).
 *
 * <p>
 * GUI ini menampilkan form input untuk data film anime, JTable untuk daftar
 * film, status tayang otomatis, dan fitur format durasi.
 * </p>
 *
 * <p>
 * Data disimpan menggunakan {@link ArrayList} dari objek {@link AnimeFilm}.
 * </p>
 *
 * @author Administrator
 * @version 1.0
 * @see AnimeFilm
 * @see Media
 */
public class GUI_AnimeFilm extends javax.swing.JFrame {

    /** List untuk menyimpan data anime film. */
    private final ArrayList<AnimeFilm> listFilm = new ArrayList<>();
    
    /** Model tabel anime film. */
    private javax.swing.table.DefaultTableModel modelFilm;

    /**
     * Constructor GUI_AnimeFilm.
     * Menginisialisasi seluruh komponen GUI dan menampilkan JFrame.
     */
    public GUI_AnimeFilm() {
        initComponents();
        setLocationRelativeTo(null);

        // DocumentListener untuk auto-update status tayang
        tfTanggal.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateStatusTayang();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateStatusTayang();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateStatusTayang();
            }
        });
    }

    /**
     * Mengupdate label status tayang secara otomatis berdasarkan input tanggal
     * rilis. Membuat objek {@link AnimeFilm} sementara untuk memanfaatkan
     * method {@code sudahTayang()}.
     */
    private void updateStatusTayang() {
        String tanggal = tfTanggal.getText().trim();
        if (tanggal.length() == 10) {
            // Buat objek sementara untuk mengecek status tayang
            AnimeFilm temp = new AnimeFilm("", "", 0, "", 0, tanggal, "");
            if (temp.sudahTayang()) {
                lblStatusTayang.setText("Status Tayang: ✅ Sudah Tayang");
                lblStatusTayang.setForeground(new Color(0, 128, 0));
            } else {
                lblStatusTayang.setText("Status Tayang: ⏳ Belum Tayang");
                lblStatusTayang.setForeground(new Color(200, 100, 0));
            }
        } else {
            lblStatusTayang.setText("Status Tayang: -");
            lblStatusTayang.setForeground(Color.BLACK);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        formPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfJudul = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfGenre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfTahun = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfStatus = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfDurasi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfTanggal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfDistributor = new javax.swing.JTextField();
        lblStatusTayang = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        centerWrapperPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        String[] kolom = { "Judul", "Genre", "Tahun", "Status", "Durasi", "Tanggal Rilis", "Distributor" };
        modelFilm = new javax.swing.table.DefaultTableModel(kolom, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tableFilm = new javax.swing.JTable();
        buttonActionPanel = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        bottomPanel = new javax.swing.JPanel();
        btnInfo = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        lblInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SPJA — Kelola Anime Film");

        formPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Data Anime Film"));
        formPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Judul:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(tfJudul, gridBagConstraints);

        jLabel2.setText("Genre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(tfGenre, gridBagConstraints);

        jLabel3.setText("Tahun Rilis:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(tfTahun, gridBagConstraints);

        jLabel4.setText("Status:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(tfStatus, gridBagConstraints);

        jLabel5.setText("Durasi (menit):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(jLabel5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(tfDurasi, gridBagConstraints);

        jLabel6.setText("Tanggal Rilis (DD-MM-YYYY):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(tfTanggal, gridBagConstraints);

        jLabel7.setText("Distributor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(jLabel7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(tfDistributor, gridBagConstraints);

        lblStatusTayang.setFont(lblStatusTayang.getFont().deriveFont(lblStatusTayang.getFont().getStyle() | java.awt.Font.BOLD));
        lblStatusTayang.setText("Status Tayang: -");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(lblStatusTayang, gridBagConstraints);

        btnTambah.setText("Tambah Film");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(btnTambah, gridBagConstraints);

        getContentPane().add(formPanel, java.awt.BorderLayout.NORTH);

        centerWrapperPanel.setLayout(new java.awt.BorderLayout(5, 5));

        tableFilm.setModel(modelFilm);
        jScrollPane1.setViewportView(tableFilm);

        centerWrapperPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        buttonActionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Aksi"));
        buttonActionPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        buttonActionPanel.add(btnSimpan);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        buttonActionPanel.add(btnHapus);

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        buttonActionPanel.add(btnBatal);

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        buttonActionPanel.add(btnClose);

        centerWrapperPanel.add(buttonActionPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(centerWrapperPanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Info Film (getInfo)"));
        bottomPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnInfo.setText("Tampilkan Info");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });
        bottomPanel.add(btnInfo);
        bottomPanel.add(filler2);

        lblInfo.setText("Pilih film dari tabel, lalu klik Tampilkan Info.");
        bottomPanel.add(lblInfo);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Aksi tombol "Tambah Film". Memvalidasi input, membuat objek
     * {@link AnimeFilm}, menyimpan ke list, dan menampilkan di JTable.
     */
    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        String judul = tfJudul.getText().trim();
        String genre = tfGenre.getText().trim();
        String sTahun = tfTahun.getText().trim();
        String status = tfStatus.getText().trim();
        String sDurasi = tfDurasi.getText().trim();
        String tanggal = tfTanggal.getText().trim();
        String distro = tfDistributor.getText().trim();

        // Validasi: cek field tidak kosong
        if (judul.isEmpty() || genre.isEmpty() || sTahun.isEmpty()
                || status.isEmpty() || sDurasi.isEmpty() || tanggal.isEmpty()
                || distro.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Semua field harus diisi!",
                    "Validasi Input", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validasi: tahun rilis harus angka
        int tahun;
        try {
            tahun = Integer.parseInt(sTahun);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "Tahun Rilis harus berupa angka!",
                    "Validasi Input", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validasi: durasi harus angka
        int durasi;
        try {
            durasi = Integer.parseInt(sDurasi);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "Durasi (menit) harus berupa angka!",
                    "Validasi Input", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Buat objek AnimeFilm (child dari Media) dan simpan
        AnimeFilm film = new AnimeFilm(judul, genre, tahun, status, durasi, tanggal, distro);
        listFilm.add(film);

        // Tambahkan ke tabel (durasi ditampilkan dalam format "Xj Ym")
        modelFilm.addRow(new Object[] {
            judul, genre, tahun, status, film.getFormatDurasi(), tanggal, distro
        });

        // Reset fields
        clearFields();

        JOptionPane.showMessageDialog(this,
                "Film \"" + judul + "\" berhasil ditambahkan!",
                "Sukses", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if (listFilm.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Tidak ada data untuk disimpan!",
                    "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        System.out.println("\n========== SIMPAN DATA ANIME FILM ==========");
        System.out.println("Total Film: " + listFilm.size());
        for (int i = 0; i < listFilm.size(); i++) {
            System.out.println((i + 1) + ". " + listFilm.get(i).getInfo());
        }
        System.out.println("===========================================\n");

        JOptionPane.showMessageDialog(this,
                "Data disimpan! Total: " + listFilm.size() + " film.\n"
                + "Lihat console untuk detail.",
                "Simpan Berhasil", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int selectedRow = tableFilm.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this,
                    "Pilih film dari tabel terlebih dahulu!",
                    "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        String judul = listFilm.get(selectedRow).getJudul();
        int confirm = JOptionPane.showConfirmDialog(this,
                "Yakin ingin menghapus film \"" + judul + "\"?",
                "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            listFilm.remove(selectedRow);
            modelFilm.removeRow(selectedRow);
            JOptionPane.showMessageDialog(this,
                    "Film \"" + judul + "\" berhasil dihapus!",
                    "Sukses", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        clearFields();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        int selectedRow = tableFilm.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this,
                    "Pilih film dari tabel terlebih dahulu!",
                    "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        AnimeFilm film = listFilm.get(selectedRow);
        lblInfo.setText(film.getInfo());

        // Juga cetak ke konsol menggunakan tampilkanDetail()
        film.tampilkanDetail();
    }//GEN-LAST:event_btnInfoActionPerformed

    /**
     * Membersihkan semua field input.
     */
    private void clearFields() {
        tfJudul.setText("");
        tfGenre.setText("");
        tfTahun.setText("");
        tfStatus.setText("");
        tfDurasi.setText("");
        tfTanggal.setText("");
        tfDistributor.setText("");
        lblStatusTayang.setText("Status Tayang: -");
        lblStatusTayang.setForeground(Color.BLACK);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_AnimeFilm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JPanel buttonActionPanel;
    private javax.swing.JPanel centerWrapperPanel;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblStatusTayang;
    private javax.swing.JTable tableFilm;
    private javax.swing.JTextField tfDistributor;
    private javax.swing.JTextField tfDurasi;
    private javax.swing.JTextField tfGenre;
    private javax.swing.JTextField tfJudul;
    private javax.swing.JTextField tfStatus;
    private javax.swing.JTextField tfTahun;
    private javax.swing.JTextField tfTanggal;
    // End of variables declaration//GEN-END:variables
}
