/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.pololer.spjaprak;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * Class GUI_Anime merupakan class GUI berbasis Java Swing yang menyediakan
 * antarmuka grafis khusus untuk mengelola data Anime Series dalam Sistem
 * Penjadwalan Tayang Anime (SPJA).
 *
 * <p>
 * GUI ini menampilkan form input untuk data anime, JTable untuk daftar anime,
 * dan fitur hitung progress tayang.
 * </p>
 *
 * <p>
 * Data disimpan menggunakan {@link ArrayList} dari objek {@link Anime}.
 * </p>
 *
 * @author Administrator
 * @version 1.0
 * @see Anime
 * @see Media
 */
public class GUI_Anime extends javax.swing.JFrame {

    /** List untuk menyimpan data anime series. */
    private final ArrayList<Anime> listAnime = new ArrayList<>();
    
    /** Model tabel anime series. */
    private javax.swing.table.DefaultTableModel modelAnime;

    /**
     * Constructor GUI_Anime.
     * Menginisialisasi seluruh komponen GUI dan menampilkan JFrame.
     */
    public GUI_Anime() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        formPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfJudul = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfGenre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfTahun = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfStatus = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfStudio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfEpisode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfMusim = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfHari = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        centerWrapperPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAnime = new javax.swing.JTable();
        buttonActionPanel = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        bottomPanel = new javax.swing.JPanel();
        progressPanel = new javax.swing.JPanel();
        btnProgress = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        lblProgress = new javax.swing.JLabel();
        infoPanel = new javax.swing.JPanel();
        btnInfo = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        lblInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SPJA — Kelola Anime Series");
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        formPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Data Anime Series"));
        formPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Judul:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(tfJudul, gridBagConstraints);

        jLabel2.setText("Genre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(tfGenre, gridBagConstraints);

        jLabel3.setText("Tahun Rilis:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(tfTahun, gridBagConstraints);

        jLabel4.setText("Status:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(tfStatus, gridBagConstraints);

        jLabel5.setText("Studio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(jLabel5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(tfStudio, gridBagConstraints);

        jLabel6.setText("Total Episode:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(tfEpisode, gridBagConstraints);

        jLabel7.setText("Musim:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(jLabel7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(tfMusim, gridBagConstraints);

        jLabel8.setText("Hari Tayang:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(jLabel8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(tfHari, gridBagConstraints);

        btnTambah.setText("Tambah Anime");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 6);
        formPanel.add(btnTambah, gridBagConstraints);

        getContentPane().add(formPanel, java.awt.BorderLayout.NORTH);

        centerWrapperPanel.setLayout(new java.awt.BorderLayout(5, 5));

        String[] kolom = { "Judul", "Genre", "Tahun", "Status", "Studio", "Episode", "Musim", "Hari Tayang" };
        modelAnime = new javax.swing.table.DefaultTableModel(kolom, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tableAnime.setModel(modelAnime);
        jScrollPane1.setViewportView(tableAnime);

        centerWrapperPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        buttonActionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Aksi"));
        buttonActionPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        buttonActionPanel.add(btnSimpan);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        buttonActionPanel.add(btnHapus);

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        buttonActionPanel.add(btnBatal);

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        buttonActionPanel.add(btnClose);

        centerWrapperPanel.add(buttonActionPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(centerWrapperPanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 10, 10));
        bottomPanel.setLayout(new java.awt.BorderLayout(5, 5));

        progressPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Hitung Progress Tayang"));
        progressPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnProgress.setText("Hitung Progress");
        btnProgress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProgressActionPerformed(evt);
            }
        });
        progressPanel.add(btnProgress);
        progressPanel.add(filler1);

        lblProgress.setFont(lblProgress.getFont().deriveFont(lblProgress.getFont().getStyle() | java.awt.Font.BOLD));
        lblProgress.setText("Progress: -");
        progressPanel.add(lblProgress);

        bottomPanel.add(progressPanel, java.awt.BorderLayout.NORTH);

        infoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Info Anime (getInfo)"));
        infoPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnInfo.setText("Tampilkan Info");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });
        infoPanel.add(btnInfo);
        infoPanel.add(filler2);

        lblInfo.setText("Pilih anime dari tabel, lalu klik Tampilkan Info.");
        infoPanel.add(lblInfo);

        bottomPanel.add(infoPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Aksi tombol "Tambah Anime". Memvalidasi input, membuat objek
     * {@link Anime}, menyimpan ke list, dan menampilkan di JTable.
     */
    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        String judul = tfJudul.getText().trim();
        String genre = tfGenre.getText().trim();
        String sTahun = tfTahun.getText().trim();
        String status = tfStatus.getText().trim();
        String studio = tfStudio.getText().trim();
        String sEps = tfEpisode.getText().trim();
        String musim = tfMusim.getText().trim();
        String hari = tfHari.getText().trim();

        // Validasi: cek field tidak kosong
        if (judul.isEmpty() || genre.isEmpty() || sTahun.isEmpty()
                || status.isEmpty() || studio.isEmpty() || sEps.isEmpty()
                || musim.isEmpty() || hari.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Semua field harus diisi!",
                    "Validasi Input", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validasi: tahun rilis harus angka
        int tahun;
        try {
            tahun = Integer.parseInt(sTahun);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "Tahun Rilis harus berupa angka!",
                    "Validasi Input", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validasi: total episode harus angka
        int totalEp;
        try {
            totalEp = Integer.parseInt(sEps);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "Total Episode harus berupa angka!",
                    "Validasi Input", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Buat objek Anime (child dari Media) dan simpan
        Anime anime = new Anime(judul, genre, tahun, status, studio, totalEp, musim, hari);
        listAnime.add(anime);

        // Tambahkan ke tabel
        modelAnime.addRow(new Object[] {
            judul, genre, tahun, status, studio, totalEp, musim, hari
        });

        // Reset fields
        clearFields();

        JOptionPane.showMessageDialog(this,
                "Anime \"" + judul + "\" berhasil ditambahkan!",
                "Sukses", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if (listAnime.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Tidak ada data untuk disimpan!",
                    "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        System.out.println("\n========== SIMPAN DATA ANIME ==========");
        System.out.println("Total Anime: " + listAnime.size());
        for (int i = 0; i < listAnime.size(); i++) {
            System.out.println((i + 1) + ". " + listAnime.get(i).getInfo());
        }
        System.out.println("=======================================\n");

        JOptionPane.showMessageDialog(this,
                "Data disimpan! Total: " + listAnime.size() + " anime.\n"
                + "Lihat console untuk detail.",
                "Simpan Berhasil", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int selectedRow = tableAnime.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this,
                    "Pilih anime dari tabel terlebih dahulu!",
                    "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        String judul = listAnime.get(selectedRow).getJudul();
        int confirm = JOptionPane.showConfirmDialog(this,
                "Yakin ingin menghapus anime \"" + judul + "\"?",
                "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            listAnime.remove(selectedRow);
            modelAnime.removeRow(selectedRow);
            JOptionPane.showMessageDialog(this,
                    "Anime \"" + judul + "\" berhasil dihapus!",
                    "Sukses", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        clearFields();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnProgressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProgressActionPerformed
        int selectedRow = tableAnime.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this,
                    "Pilih anime dari tabel terlebih dahulu!",
                    "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        String input = JOptionPane.showInputDialog(this,
                "Masukkan episode saat ini untuk \""
                + listAnime.get(selectedRow).getJudul() + "\":");

        if (input == null || input.trim().isEmpty()) {
            return;
        }

        int epSaatIni;
        try {
            epSaatIni = Integer.parseInt(input.trim());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "Input harus berupa angka!",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Anime anime = listAnime.get(selectedRow);
        double progress = anime.getProgressTayang(epSaatIni);
        lblProgress.setText(String.format("Progress: %.1f%% (%d / %d episode)",
                progress, epSaatIni, anime.getTotalEpisode()));
        lblProgress.setForeground(progress >= 100.0
                ? new Color(0, 128, 0) : new Color(0, 0, 180));
    }//GEN-LAST:event_btnProgressActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        int selectedRow = tableAnime.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this,
                    "Pilih anime dari tabel terlebih dahulu!",
                    "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        Anime anime = listAnime.get(selectedRow);
        lblInfo.setText(anime.getInfo());

        // Juga cetak ke konsol menggunakan tampilkanDetail()
        anime.tampilkanDetail();
    }//GEN-LAST:event_btnInfoActionPerformed

    /**
     * Membersihkan semua field input.
     */
    private void clearFields() {
        tfJudul.setText("");
        tfGenre.setText("");
        tfTahun.setText("");
        tfStatus.setText("");
        tfStudio.setText("");
        tfEpisode.setText("");
        tfMusim.setText("");
        tfHari.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Anime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnProgress;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JPanel buttonActionPanel;
    private javax.swing.JPanel centerWrapperPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel formPanel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblProgress;
    private javax.swing.JPanel progressPanel;
    private javax.swing.JTable tableAnime;
    private javax.swing.JTextField tfEpisode;
    private javax.swing.JTextField tfGenre;
    private javax.swing.JTextField tfHari;
    private javax.swing.JTextField tfJudul;
    private javax.swing.JTextField tfMusim;
    private javax.swing.JTextField tfStatus;
    private javax.swing.JTextField tfStudio;
    private javax.swing.JTextField tfTahun;
    // End of variables declaration//GEN-END:variables
}
