/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 */
package com.pololer.spjaprak;

/**
 * Class Spjaprak merupakan class utama (main entry point) dari aplikasi
 * Sistem Penjadwalan Tayang Anime (SPJA).
 *
 * @author Administrator
 * @version 1.0
 */
public class Spjaprak extends javax.swing.JFrame {

    /**
     * Creates new form Spjaprak
     */
    public Spjaprak() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblTitle = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuHome = new javax.swing.JMenu();
        menuItemExit = new javax.swing.JMenuItem();
        menuForm = new javax.swing.JMenu();
        menuItemAnime = new javax.swing.JMenuItem();
        menuItemFilm = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SPJA — Sistem Penjadwalan Tayang Anime");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lblTitle.setFont(lblTitle.getFont().deriveFont(lblTitle.getFont().getStyle() | java.awt.Font.BOLD, lblTitle.getFont().getSize()+6));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Menu Program");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(lblTitle, gridBagConstraints);

        menuHome.setText("Home");

        menuItemExit.setText("Keluar");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        menuHome.add(menuItemExit);

        jMenuBar1.add(menuHome);

        menuForm.setText("Menu");

        menuItemAnime.setText("Kelola Anime Series");
        menuItemAnime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAnimeActionPerformed(evt);
            }
        });
        menuForm.add(menuItemAnime);

        menuItemFilm.setText("Kelola Anime Film");
        menuItemFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFilmActionPerformed(evt);
            }
        });
        menuForm.add(menuItemFilm);

        jMenuBar1.add(menuForm);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void menuItemAnimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAnimeActionPerformed
        new GUI_Anime().setVisible(true);
    }//GEN-LAST:event_menuItemAnimeActionPerformed

    private void menuItemFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFilmActionPerformed
        new GUI_AnimeFilm().setVisible(true);
    }//GEN-LAST:event_menuItemFilmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Implementasi Exception Handling secara global untuk menangkap unhandled exception
        // dan menampilkannya dalam bentuk pop-up
        Thread.setDefaultUncaughtExceptionHandler((Thread t, Throwable e) -> {
            javax.swing.JOptionPane.showMessageDialog(null,
                    "Terjadi exception yang tidak terduga:\n" + e.getMessage(),
                    "System Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        });

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Spjaprak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JMenu menuForm;
    private javax.swing.JMenu menuHome;
    private javax.swing.JMenuItem menuItemAnime;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemFilm;
    // End of variables declaration//GEN-END:variables
}
